pipeline {
    agent { label 'ubuntu-agent' }

    parameters {
        string(name: 'RETRY_COUNT', defaultValue: '3', description: 'Number of retries for failed tests')
    }

    environment {
        REPORT_DIR = 'reports'
        SLACK_CHANNEL = '#jenkins-notifications'
        SLACK_USER = 'jenkins-bot'
        REPORT_URL = "${env.BUILD_URL}artifact/reports/index.html"
    }

    stages {
        stage('Prepare Workspace') {
            steps {
                sh "mkdir -p ${env.WORKSPACE}/${REPORT_DIR}"
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                ansiColor('xterm') {
                    sh 'npm install'
                }
            }
        }

        stage('Run & Retry Tests') {
            steps {
                ansiColor('xterm') {
                    script {
                        def retries = params.RETRY_COUNT.toInteger()
                        def allTests = [
                            "LoginTest","SignupTest","SearchTest","CheckoutTest","ProfileUpdateTest",
                            "LogoutTest","AddToCartTest","RemoveFromCartTest","PaymentTest",
                            "OrderHistoryTest","FilterTest","SortTest","WishlistTest","ReviewTest","NotificationTest"
                        ]
                        def failedTests = allTests
                        def passedTests = []

                        for (int attempt = 1; attempt <= retries; attempt++) {
                            if (failedTests.isEmpty()) break
                            echo "\u001B[33m🔁 Attempt #${attempt} for tests: ${failedTests}\u001B[0m"

                            def currentFailures = []
                            for (test in failedTests) {
                                def passed = (new Random().nextBoolean()) // Replace with real test command
                                if (passed) {
                                    echo "\u001B[32m✅ ${test} passed\u001B[0m"
                                    passedTests << test
                                } else {
                                    echo "\u001B[31m❌ ${test} failed\u001B[0m"
                                    currentFailures << test
                                }
                            }
                            failedTests = currentFailures
                        }

                        // Save failures for Slack
                        writeFile file: "${REPORT_DIR}/failures.txt", text: failedTests.join('\n')

                        // Generate a friendly HTML summary for Jenkins UI
                        def summaryHtml = """
                        <html>
                        <head>
                            <style>
                                body { font-family: Arial; margin: 20px; }
                                h2 { color: #333; }
                                .passed { color: green; }
                                .failed { color: red; }
                                .retry { color: orange; }
                                .summary-box {
                                    background: #f9f9f9;
                                    border: 1px solid #ccc;
                                    padding: 10px;
                                    border-radius: 5px;
                                    width: 80%;
                                }
                            </style>
                        </head>
                        <body>
                            <h2>🧪 Test Execution Summary</h2>
                            <div class="summary-box">
                                <p><b>Retries Used:</b> ${retries}</p>
                                <p><b>Passed Tests:</b> <span class="passed">${passedTests.join(', ') ?: 'None'}</span></p>
                                <p><b>Failed Tests:</b> <span class="failed">${failedTests.join(', ') ?: 'None'}</span></p>
                                <p><b>Report:</b> <a href="${env.REPORT_URL}" target="_blank">Open Detailed Report</a></p>
                            </div>
                            <p>Generated by Jenkins CI Bot 🤖</p>
                        </body>
                        </html>
                        """
                        writeFile file: "${REPORT_DIR}/summary.html", text: summaryHtml

                        // Debug check - verify file exists
                        sh 'ls -R reports || echo "No reports directory found"'
                    }
                }
            }
        }

        stage('Report & Notify') {
            steps {
                ansiColor('xterm') {
                    script {
                        def failedTestsList = fileExists("${REPORT_DIR}/failures.txt") ? readFile("${REPORT_DIR}/failures.txt").trim() : ""
                        def isFailure = failedTestsList && failedTestsList != ""
                        def failedTestsFormatted = isFailure ? failedTestsList.split('\n').collect { it }.join(', ') : "None"

                        slackSend(
                            channel: env.SLACK_CHANNEL,
                            color: isFailure ? '#FFA500' : '#36a64f',
                            message: """${isFailure ? ':warning: Build Unstable — Some Tests Failed' : ':white_check_mark: Build Successful — All Tests Passed'}
• Failed Tests: ${failedTestsFormatted}
• Retries Used: ${params.RETRY_COUNT}
• Duration: ${currentBuild.durationString}
• Report: <${env.REPORT_URL}|Open HTML Report>
:robot_face: Jenkins CI Bot"""
                        )

                        if (isFailure) {
                            currentBuild.result = 'UNSTABLE'
                        }
                    }
                }
            }
        }

        stage('Publish & Archive Summary') {
            steps {
                script {
                    try {
                        // Try publishing HTML summary
                        publishHTML([
                            reportDir: "${REPORT_DIR}",
                            reportFiles: 'summary.html',
                            reportName: '🧾 Test Summary'
                        ])
                        echo "✅ HTML report published successfully."
                    } catch (err) {
                        echo "⚠️ Failed to publish HTML summary: ${err.message}"
                    }

                    // Always archive for download
                    archiveArtifacts artifacts: "${REPORT_DIR}/summary.html", onlyIfSuccessful: false
                    echo "📄 Summary archived at: ${env.BUILD_URL}artifact/${REPORT_DIR}/summary.html"
                }
            }
        }
    }
}
